'use strict';
const B = window.MONTHLY_REPORTS;
const el = id => document.getElementById(id);
const fmt = (v, digits=1, signed=false) => v===null ? 'No disponible' : new Intl.NumberFormat('es-AR',{minimumFractionDigits:digits,maximumFractionDigits:digits,signDisplay:signed?'exceptZero':'auto'}).format(Math.abs(v)<.5*10**-digits?0:v);
const rate = v => v===null ? 'No disponible' : `${fmt(v,1,true)}%`;
const monthName = p => new Date(p+'T12:00:00Z').toLocaleDateString('es-AR',{month:'long',year:'numeric',timeZone:'UTC'});
el('report-period').innerHTML=B.reports.slice().reverse().map(r=>`<option value="${r.period}">${r.title}</option>`).join('');
const requested = location.hash.slice(1);
if (B.reports.some(r=>r.period===requested)) el('report-period').value=requested;
el('vintage').textContent=`Descarga: ${B.source.downloaded_at}`;
el('sector-source').href=B.source.api_query;
el('sector-hash').textContent=B.source.sha256;
el('ai-conclusion').textContent=B.evidence.conclusion;
el('ai-vintage').textContent=`Revisión de fuentes: ${B.evidence.reviewed_at}. Contexto actual, no información necesariamente disponible en cada mes histórico.`;
el('ai-interpretation').textContent=B.evidence.interpretation;
el('ai-next').textContent=B.evidence.next_data;
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const W=B.workbench;
el('metals-narrative').textContent=W.metals.narrative;
el('quality-snapshot').textContent=`Construcción: ${W.as_of}. ${W.snapshot_note}`;
el('quality-partial').textContent=`Meses parciales de la captura eléctrica, excluidos del cierre: ${W.partial_periods.join(', ')||'ninguno'}.`;
el('quality-sources').innerHTML=W.sources.map(s=>`<article class="workbench-card"><h3>${esc(s.label)}</h3><dl><dt>Último período completo</dt><dd>${esc(s.latest_period)}</dd><dt>Captura</dt><dd>${esc(s.captured_at)}</dd><dt>Publicación de esta versión</dt><dd>${esc(s.published_at||'No verificada')}</dd><dt>Cobertura</dt><dd>${esc(s.coverage)}</dd><dt>Condición</dt><dd>${esc(s.condition)}</dd></dl><p><b>Próxima comprobación:</b> ${esc(s.next_check)}</p><a href="${esc(s.source_url)}" target="_blank" rel="noopener">Fuente original ↗</a><details><summary>Versión: SHA-256</summary><code>${esc(s.sha256)}</code></details></article>`).join('');
el('casebook-scope').textContent=W.metals.casebook.scope;
el('casebook-hypotheses').innerHTML=W.metals.casebook.hypotheses.map(h=>`<details class="hypothesis"><summary>${esc(h.title)} — ${esc(h.status)}</summary><dl><dt>Evidencia a favor o plausibilidad</dt><dd>${esc(h.support)}</dd><dt>Evidencia contraria o límite</dt><dd>${esc(h.counter)}</dd><dt>Dato decisivo que falta</dt><dd>${esc(h.needed)}</dd><dt>Acción de investigación</dt><dd>${esc(h.action)}</dd></dl><a href="${esc(h.source_url)}" target="_blank" rel="noopener">Fuente relacionada ↗</a></details>`).join('');
el('operations-state').textContent=`${W.operations.period||'Cohorte'}: ${W.operations.state}. Estado calculado al construir el sitio, no vigilancia en vivo.`;
el('operations-steps').innerHTML=W.operations.steps.map(s=>`<li>${esc(s)}</li>`).join('');
el('document-assistant-status').textContent=`${W.document_assistant.status}. Exactitud: no medida. ${W.document_assistant.description}`;
el('ai-evidence').innerHTML=B.evidence.indicators.map(e=>`<tr><th scope="row">${esc(e.metric)}<small>${esc(e.geography)} · ${esc(e.period)}</small></th><td>${e.value===null?'No informado':fmt(e.value,0)+' '+esc(e.unit)}</td><td>${esc(e.status)}</td><td>${esc(e.limitation)} <a href="${esc(B.evidence.sources.find(s=>s.id===e.source_id).url)}" target="_blank" rel="noopener">Fuente ↗</a></td></tr>`).join('');
let selected;
let printDetails=[];
window.addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('.workbench details')].map(d=>[d,d.open]);printDetails.forEach(([d])=>{d.open=true;});});
window.addEventListener('afterprint',()=>{printDetails.forEach(([d,open])=>{d.open=open;});printDetails=[];});
function render(){
  const r=B.reports.find(r=>r.period===el('report-period').value);selected=r;
  const v=r.sector_review;
  const e=r.executive;
  el('executive-period').textContent=r.title;
  el('executive-ordering').textContent=e.ordering;
  el('executive-next').textContent=e.next_action;
  el('executive-boundary').textContent=e.boundary;
  el('executive-findings').innerHTML=e.findings.map(f=>`<article class="workbench-card"><h3>${esc(f.label)}</h3><p class="finding-value">${rate(f.yoy_percent)} · ${fmt(f.delta_mw,1,true)} MW</p><p><b>Intensidad:</b> ${esc(f.intensity)}. Persistencia: ${f.persistent===null?'no evaluable':f.persistent?'sí':'no'}.</p><p><b>Calidad:</b> ${esc(f.quality)}.</p><p><b>Qué comprobar:</b> ${esc(f.action)}</p></article>`).join('');
  el('monthly-alert-note').textContent=v.alert_note;
  el('monthly-alert-scope').textContent=v.scope;
  el('monthly-production-note').textContent=v.production_note;
  el('monthly-registry-note').textContent=v.registry_note;
  el('monthly-alert-rows').innerHTML=v.rows.map(x=>`<tr><th scope="row">${esc(x.label)}<small class="quality-label">Calidad: ${esc(x.quality)}</small></th><td>${rate(x.yoy_percent)}</td><td>${esc(x.status.replaceAll('_',' '))}</td></tr>`).join('');
  el('monthly-production-rows').innerHTML=v.production.map(x=>`<tr><th scope="row">${esc(x.label)}</th><td>${rate(x.electricity_yoy_percent)}</td><td>${rate(x.yoy_percent)}</td></tr>`).join('');
  el('monthly-alert-rows').closest('.table-wrap').hidden=!v.rows.length;
  el('monthly-production-rows').closest('.table-wrap').hidden=!v.production.length;
  el('ai-local').textContent=r.ai_diagnosis;
  document.title=`Informe ${r.title} · Energy Demand Lab`;
  el('report-month').textContent=r.title;
  el('headline').textContent=r.headline;
  el('summary').textContent=r.summary;
  el('total').innerHTML=`${fmt(r.total.current_gwh)} <small>GWh</small>`;
  el('previous').textContent=`${fmt(r.total.previous_gwh)} GWh en ${monthName(r.previous_period)}`;
  el('yoy').textContent=rate(r.total.yoy_percent);
  el('delta-total').textContent=`${fmt(r.total.delta_gwh,1,true)} GWh frente al mismo mes del año anterior`;
  const y=r.ytd;
  el('ytd-rate').textContent=y?rate(y.yoy_percent):'No disponible';
  const through=new Date(r.period+'T12:00:00Z').toLocaleDateString('es-AR',{month:'long',timeZone:'UTC'});
  el('ytd-label').textContent=y?`Enero–${through} · ${fmt(y.current_gwh)} GWh`:'Faltan meses para comparar acumulados completos';
  const scale=Math.max(...r.sectors.map(s=>Math.abs(s.delta_gwh)),1);
  el('sector-bars').innerHTML=r.sectors.map(s=>`<div class="sector-row"><span>${s.label}</span><div class="sector-track" aria-hidden="true"><div class="sector-fill ${s.delta_gwh<0?'negative':''}" style="width:${Math.abs(s.delta_gwh)/scale*100}%"></div></div><strong>${fmt(s.delta_gwh,1,true)} GWh</strong></div>`).join('');
  el('sector-caption').textContent=`${r.title} frente a ${monthName(r.previous_period)} · cifras redondeadas`;
  el('sector-rows').innerHTML=r.sectors.map(s=>`<tr><th scope="row">${s.label}</th><td>${fmt(s.current_gwh)}</td><td>${rate(s.yoy_percent)}</td><td>${fmt(s.delta_gwh,1,true)}</td><td>${fmt(s.contribution_pp,2,true)}</td><td>${fmt(s.share_percent)}%</td></tr>`).join('');
  el('sector-total').innerHTML=`<tr><th scope="row">Total</th><td>${fmt(r.total.current_gwh)}</td><td>${rate(r.total.yoy_percent)}</td><td>${fmt(r.total.delta_gwh,1,true)}</td><td>${fmt(r.total.yoy_percent,2,true)}</td><td>100,0%</td></tr>`;
  el('ytd-summary').textContent=y?`Entre enero y ${through} de ${r.period.slice(0,4)} se acumularon ${fmt(y.current_gwh)} GWh, frente a ${fmt(y.previous_gwh)} GWh en los mismos meses del año anterior (${rate(y.yoy_percent)}).`:'No se calcula un acumulado cuando faltan meses en cualquiera de los dos años.';
  el('ytd-sectors').innerHTML=y?y.sectors.map(s=>`<div class="ytd-sector"><span>${s.label}</span><strong>${rate(s.yoy_percent)}</strong><small>${fmt(s.current_gwh)} GWh acumulados</small></div>`).join(''):'';
  el('report-source-note').textContent=`Mes analizado: ${r.title}. Fuente descargada el ${B.source.downloaded_at}. Serie sectorial: ${B.source.coverage.start.slice(0,7)} a ${B.source.coverage.end.slice(0,7)}. Actualización manual.`;
}
function download(content, type, filename){const url=URL.createObjectURL(new Blob(['\ufeff',content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
el('report-period').onchange=()=>{location.hash=el('report-period').value;render();};
window.addEventListener('hashchange',()=>{if(B.reports.some(r=>r.period===location.hash.slice(1))){el('report-period').value=location.hash.slice(1);render();}});
el('export-text').onclick=()=>download(selected.text,'text/plain;charset=utf-8',`informe-energia-${selected.period.slice(0,7)}.txt`);
el('export-sectors').onclick=()=>download(selected.csv,'text/csv;charset=utf-8',`sectores-${selected.period.slice(0,7)}.csv`);
el('print-report').onclick=()=>window.print();render();
