const { chromium } = require('playwright');
const path = require('path');
const assert = require('assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1440,height:1080}});
  const errors=[];
  page.on('pageerror', error=>errors.push(error.message));
  await page.goto('file://' + path.resolve(__dirname,'../dashboard/index.html'));
  await page.waitForSelector('#chart svg');
  assert.match(await page.locator('#forecast').innerText(), /10\.578,3/);
  assert.equal(await page.locator('#history tr').count(),128);
  assert.match(await page.locator('#prospective-summary').innerText(),/1 pronóstico pendiente/);
  assert.match(await page.locator('#forecasts').innerText(),/Pendiente/);
  await page.selectOption('#season','shoulder');
  assert.equal(await page.locator('#history tr').count(),63);
  assert.match(await page.locator('#bars').innerText(),/645,8/);
  await page.selectOption('#range','0');
  assert.equal(await page.locator('#month').getAttribute('max'),'307');
  await page.locator('#month').focus();
  await page.keyboard.press('Home');
  assert.match(await page.locator('#monthValue').innerText(),/2001/);
  const downloadPromise=page.waitForEvent('download');
  await page.click('#download');
  const download=await downloadPromise;
  assert.equal(download.suggestedFilename(),'energy-demand-pronosticos.csv');
  await page.selectOption('#range','36');
  await page.selectOption('#season','all');
  await page.screenshot({path:path.resolve(__dirname,'../dashboard/desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.resolve(__dirname,'../dashboard/mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Dashboard checked: values, seasonal filter, full history, keyboard, CSV download, mobile overflow, no browser errors.');
})().catch(error=>{console.error(error);process.exit(1)});
